/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogChannelRouteImport } from './routes/blog.channel'
import { Route as BlogReceiverRouteImport } from './routes/blog.receiver'
import { Route as BlogTransmitterRouteImport } from './routes/blog.transmitter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogChannelRoute = BlogChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => BlogRoute,
} as any)
const BlogReceiverRoute = BlogReceiverRouteImport.update({
  id: '/receiver',
  path: '/receiver',
  getParentRoute: () => BlogRoute,
} as any)
const BlogTransmitterRoute = BlogTransmitterRouteImport.update({
  id: '/transmitter',
  path: '/transmitter',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/channel': typeof BlogChannelRoute
  '/blog/receiver': typeof BlogReceiverRoute
  '/blog/transmitter': typeof BlogTransmitterRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/channel': typeof BlogChannelRoute
  '/blog/receiver': typeof BlogReceiverRoute
  '/blog/transmitter': typeof BlogTransmitterRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/channel': typeof BlogChannelRoute
  '/blog/receiver': typeof BlogReceiverRoute
  '/blog/transmitter': typeof BlogTransmitterRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/blog/channel'
    | '/blog/receiver'
    | '/blog/transmitter'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/channel' | '/blog/receiver' | '/blog/transmitter' | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/blog/channel'
    | '/blog/receiver'
    | '/blog/transmitter'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/channel': {
      id: '/blog/channel'
      path: '/channel'
      fullPath: '/blog/channel'
      preLoaderRoute: typeof BlogChannelRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/receiver': {
      id: '/blog/receiver'
      path: '/receiver'
      fullPath: '/blog/receiver'
      preLoaderRoute: typeof BlogReceiverRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/transmitter': {
      id: '/blog/transmitter'
      path: '/transmitter'
      fullPath: '/blog/transmitter'
      preLoaderRoute: typeof BlogTransmitterRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogChannelRoute: typeof BlogChannelRoute
  BlogReceiverRoute: typeof BlogReceiverRoute
  BlogTransmitterRoute: typeof BlogTransmitterRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogChannelRoute: BlogChannelRoute,
  BlogReceiverRoute: BlogReceiverRoute,
  BlogTransmitterRoute: BlogTransmitterRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
